// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tarea2_RegistroEstudiantes_RolesWPF.DAL;

namespace Tarea2_RegistroEstudiantes_RolesWPF.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20210907201222_Migracion_Inicial")]
    partial class Migracion_Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("Tarea2_RegistroEstudiantes_RolesWPF.Entidades.Adicionales", b =>
                {
                    b.Property<int>("AdicionalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<float>("Puntos")
                        .HasColumnType("REAL");

                    b.HasKey("AdicionalId");

                    b.ToTable("Adicionales");
                });

            modelBuilder.Entity("Tarea2_RegistroEstudiantes_RolesWPF.Entidades.Estudiantes", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombres")
                        .HasColumnType("TEXT");

                    b.Property<float>("PuntosExtra")
                        .HasColumnType("REAL");

                    b.Property<int>("Semestre")
                        .HasColumnType("INTEGER");

                    b.HasKey("EstudianteId");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("Tarea2_RegistroEstudiantes_RolesWPF.Entidades.Nacionalidades", b =>
                {
                    b.Property<int>("NacionalidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nacionalidad")
                        .HasColumnType("TEXT");

                    b.HasKey("NacionalidadId");

                    b.ToTable("Nacionalidades");
                });

            modelBuilder.Entity("Tarea2_RegistroEstudiantes_RolesWPF.Entidades.Tareas", b =>
                {
                    b.Property<int>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<float>("Puntos")
                        .HasColumnType("REAL");

                    b.HasKey("TareaId");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("Tarea2_RegistroEstudiantes_RolesWPF.Entidades.TareasDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Requerimiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("TareaId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("TareaId");

                    b.ToTable("TareasDetalle");
                });

            modelBuilder.Entity("Tarea2_RegistroEstudiantes_RolesWPF.Entidades.TareasDetalle", b =>
                {
                    b.HasOne("Tarea2_RegistroEstudiantes_RolesWPF.Entidades.Tareas", null)
                        .WithMany("Detalle")
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tarea2_RegistroEstudiantes_RolesWPF.Entidades.Tareas", b =>
                {
                    b.Navigation("Detalle");
                });
#pragma warning restore 612, 618
        }
    }
}
